### ISSUE TITLE
Querying pages set as child throws an error when WPML is enabled

### ISSUE THREAD

**Issue by juanramoncarceles** [rburgst/wp-graphql-wpml#5] opened 2020-10-23 13:55 UTC
Hi,

I am getting an error when querying pages that are set as child of other pages, and it seems related to WPML.
The error says: "_SyntaxError: Unexpected token < in JSON at position 0_".

![wpgraphql-with-wpml-error-query-child-page](https://user-images.githubusercontent.com/31431405/97012018-b183d380-1547-11eb-832a-6cdfaf18bb06.png)

If I have only WPGraphQL enabled it works fine and I can fetch all the pages. However if I enable WPML I get this error when fetching any page that has a parent. It doesn't matter if the pages have translations or not.

Has anybody experienced something similar?

Thanks in advance for any feedback!

**Comment by jcoryalvernaz** [comment] 2020-11-13 23:45
> Hi,
> 
> I am getting an error when querying pages that are set as child of other pages, and it seems related to WPML.
> The error says: "_SyntaxError: Unexpected token < in JSON at position 0_".
> 
> ![wpgraphql-with-wpml-error-query-child-page](https://user-images.githubusercontent.com/31431405/97012018-b183d380-1547-11eb-832a-6cdfaf18bb06.png)
> 
> If I have only WPGraphQL enabled it works fine and I can fetch all the pages. However if I enable WPML I get this error when fetching any page that has a parent. It doesn't matter if the pages have translations or not.
> 
> Has anybody experienced something similar?
> 
> Thanks in advance for any feedback!

@juanramoncarceles 
We are experiencing a similar issue where querying for a custom post type returns the HTML. Curious as to what version of WPML you are running and if you were able to resolve your issue?

**Comment by rburgst** [comment] 2020-11-14 06:26
please also take a look at the wordpress debug log, it might give you a hint of whats going wrong.
You will definitely need to be using a recent version of wpml for this plugin to work.

**Comment by juanramoncarceles** [comment] 2020-11-14 12:29
> You will definitely need to be using a recent version of wpml for this plugin to work.

@rburgst I am pretty sure I was using the latest version of WPML.
I remember getting nothing in the debug log, however I am not an expert in WordPress.

> Curious as to what version of WPML you are running and if you were able to resolve your issue?

@jcoryalvernaz I was not able to fix the issue, and I also faced this limitation #4 so unfortunately I had to change to Polylang.

In any case I will try to take a look at this again in the future in case something has changed.

**Comment by tokrima** [comment] 2020-11-15 20:10
I'm getting the same error _"SyntaxError: Unexpected token < in JSON at position 0"_ when querying custom post types. I have WPML 4.4.5. WP GraphQL is the latest 0.15.3. 
![image](https://user-images.githubusercontent.com/36506132/99195589-508a9c80-278f-11eb-833d-3f70fab3205c.png)

**Comment by rburgst** [comment] 2020-11-16 07:32
@tokrima can you check your browser network tab what error you are getting?

**Comment by tokrima** [comment] 2020-11-16 13:23
> @tokrima can you check your browser network tab what error you are getting?

I get 301 status from /index.php?graphql
Initiator is line 63 from `/plugins/wp-graphql/src/Admin/GraphiQL/app/build/static/js/App.js`
It's the fetcher function `graphQLFetcher`

**Comment by rburgst** [comment] 2020-11-16 17:04
hmm, that doesnt really help. Could you try to connect with a dedicated graphql client such as https://insomnia.rest/ or postman and point it to http://wordpress-host/graphql

**Comment by tokrima** [comment] 2020-11-16 20:15
> hmm, that doesnt really help. Could you try to connect with a dedicated graphql client such as https://insomnia.rest/ or postman and point it to http://wordpress-host/graphql

Well, the response is the full html page of the latest cpt post :) 
![image](https://user-images.githubusercontent.com/36506132/99303206-34ebc880-2859-11eb-8971-dcabf9ea63d9.png)

**Comment by rburgst** [comment] 2020-11-17 05:18
Hm, the only thing that I can think of is to enable debugging in your wordpress instance by setting the following values in your `wp-config.php`:
```
define( 'WP_DEBUG', true );
define( 'WP_DEBUG_LOG', true );
define( 'GRAPHQL_DEBUG', true );
```

**Comment by tokrima** [comment] 2020-11-17 08:52
> Hm, the only thing that I can think of is to enable debugging in your wordpress instance by setting the following values in your `wp-config.php`:
> 
> ```
> define( 'WP_DEBUG', true );
> define( 'WP_DEBUG_LOG', true );
> define( 'GRAPHQL_DEBUG', true );
> ```

Had them on but unfortunately no errors logged. CPTs are working for you? What versions of WPML and WP GraphQL are you using?

**Comment by juanramoncarceles** [comment] 2020-11-17 09:25
@tokrima Also in my case I remember no errors logged. I am just curious if any of you are able to query pages set as child or if you also get this same error? Because if this is working for you then the cpt might be a different error.
In any case it looks like it is receiving the raw HTML instead of a JSON response no?

**Comment by rburgst** [comment] 2020-11-17 09:49
@tokrima yes, custom post types do work for me. I am using

* WPGraphql 0.14.0
* WPGraphql for ACF 0.4.0
* WPGraphql WPML (latest)
* WPGraphQL Custom Post Type UI (1.1)
* WPML Multilingual CMS: 4.4.4
* WPML String Translation: 3.1.4
* WPML Translation Management: 2.10.2
* Advanced Custom Fields Multilingual: 1.7.3

**Comment by tokrima** [comment] 2020-11-17 10:17
@juanramoncarceles Yes, querying pages set as child gives the same error for me.

**Comment by rburgst** [comment] 2020-11-19 07:13
does this query work when you disable `wp-graphql-wpml`?

**Comment by Ninodevo** [comment] 2020-11-19 13:25
Hi all, I have the same error on CPTs. I figured out that this happens after WPGraphQL 0.14.0. When I use WPGraphQL 0.13.3. It works

**Comment by tokrima** [comment] 2020-11-19 17:35
Yes, I can confirm. CPTs work with WPGraphQL 0.13.3. and WPML Multilingual CMS 4.4.4 and 4.4.5. Still error with child page query.

**Comment by rburgst** [comment] 2020-11-20 07:50
so to summarize, `wp-graphql-wpml` wont fix a previously non-working `wp-graphql` setup. All it does is disable a few wpml filters which prevented translated content (usually the content in a non-default language) from being returned

**Comment by rburgst** [comment] 2020-11-20 08:29
actually I found out the reason for the 302. Unfortunately it doesnt seem to be fixable by a plugin, so you have to patch the WPML code:
in `plugins/sitepress-multilingual-cms/classes/query-filtering/class-wpml-query-parser.php`
```php
        function parse_query( $q ) {
                if ( $this->sitepress->get_wp_api()->is_admin()
                     && ! $this->sitepress->get_wp_api()->constant( 'DOING_AJAX' )
                ) {
                        return $q;
                }

                $q = apply_filters( 'wpml_pre_parse_query', $q );

                list( $q, $redir_pid ) = $this->maybe_adjust_name_var( $q );
                // ADD THIS: to disable redirect
                $redir_pid = false;
```

**Comment by Ninodevo** [comment] 2020-11-20 08:46
@rburgst great job!. We can actually just disable the redirect with a filter so we don't mess up the WPML code.
`add_filter('wpml_is_redirected', [$this, 'disable_wpml_is_redirected'], 10, 3);

public function disable_wpml_is_redirected( $redirect, $post_id, $query ) {
		return false;
	}
`

**Comment by Ninodevo** [comment] 2020-11-20 08:47
@rburgst great job!. We can actually just disable the redirect with a filter so we don't mess up the WPML code.

``` 
add_filter('wpml_is_redirected', [$this, 'disable_wpml_is_redirected'], 10, 3);

public function disable_wpml_is_redirected( $redirect, $post_id, $query ) {
return false;
}

**Comment by rburgst** [comment] 2020-11-20 09:22
@Ninodevo unfortunately this does not help, since this hook is either not called or called too late.
I am currently experimenting with using `WP_ADMIN` which is a crud sledgehammer but at least it seems to work with my wpml version.
```
function wpgraphqlwpml_action_init()
{
    if (!wpgraphqlwpml_is_graphql_request()) {
        return;
    }

    // prevent wpml to interfere (redirect to translated pages) on every graphql query
    define ('WP_ADMIN', TRUE);
```

**Closed** 2020-11-20 09:28 UTC

**Comment by Ninodevo** [comment] 2020-11-20 09:39
I'm using WPML 4.4.5. (all latest versions) WPGraphQL 1.0. And it works for CPTS and Child Pages in my setup (using the filter I suggested).

@tokrima can you try this filter? and see if it works for you

**Comment by rburgst** [comment] 2020-11-20 09:40
I still have 4.4.4, maybe this has been added in 4.4.5

**Comment by rburgst** [comment] 2020-11-20 09:42
can you try the latest version (the one with `define ('WP_ADMIN', TRUE);`) and see if this also works?

**Comment by Ninodevo** [comment] 2020-11-20 12:48
@rburgst Yes it works with WP_ADMIN on true aswell

**Comment by wcoppens** [comment] 2021-02-10 08:00
@rburgst Although the WP_ADMIN to true solution works well in certain cases. It also introduces compatibility issues. 

The new issue when using `define ('WP_ADMIN', TRUE);` we can't use the Cart functionality of the WPGraphQL WooCommerce (WooGraphQL) package. Somehow having this flag set to true results in a 'null' Cart from `WC()->cart`. On the other hand, the Product query of the package can't work without the flag due to the redirect.

In this case we are forced to make code changes directly inside the wpml package or did you find another solution in the meantime?

Thanks!
