### ISSUE TITLE
Add a locale "where" arg

### ISSUE THREAD

**Issue by Hunscuzzy** [rburgst/wp-graphql-wpml#18] opened 2021-05-13 07:18 UTC
Hello @rburgst,

Thanks for working on this plugin.

I would like to add a "where" argument in the GraphQL query to be able to fetch only one language by one language. It can seems a little bit strange but it's just because I will use 2 domains, then, I will deploy my app twice and the idea is to use env var.

So, how can I do it?

Thanks again!

**Comment by eliawk** [comment] 2021-05-14 10:01
same here

**Comment by rburgst** [comment] 2021-05-18 05:30
hi, unfortunately this is currently not yet possible, when I have some extra time, I will try to make this happen.

**Comment by rburgst** [comment] 2021-05-18 05:31
duplicate of #13

**Closed by rburgst** 2021-05-18 05:31 UTC
